version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: $${postgres.db}
      POSTGRES_USER: $${postgres.user}
      POSTGRES_PASSWORD: $${postgres.password}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: intellij
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: $${spring.datasource.url}
      SPRING_DATASOURCE_USERNAME: $${spring.datasource.username}
      SPRING_DATASOURCE_PASSWORD: $${spring.datasource.password}
    depends_on:
      - db

volumes:
  postgres-data: