config:
  file:
    path: "config.json"

spring:
  datasource:
    url: ""
    username: ""
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
